<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert([

		['name' => 'EL ENCANTO', 'state_id' => '1'],
		['name' => 'LA CHORRERA', 'state_id' => '1'],
		['name' => 'LA PEDRERA', 'state_id' => '1'],
		['name' => 'LA VICTORIA', 'state_id' => '1'],
		['name' => 'LETICIA', 'state_id' => '1'],
		['name' => 'MIRITI', 'state_id' => '1'],
		['name' => 'PUERTO ALEGRIA', 'state_id' => '1'],
		['name' => 'PUERTO ARICA', 'state_id' => '1'],
		['name' => 'PUERTO NARIÑO', 'state_id' => '1'],
		['name' => 'PUERTO SANTANDER', 'state_id' => '1'],
		['name' => 'TURAPACA', 'state_id' => '1'],
		['name' => 'ABEJORRAL', 'state_id' => '2'],
		['name' => 'ABRIAQUI', 'state_id' => '2'],
		['name' => 'ALEJANDRIA', 'state_id' => '2'],
		['name' => 'AMAGA', 'state_id' => '2'],
		['name' => 'AMALFI', 'state_id' => '2'],
		['name' => 'ANDES', 'state_id' => '2'],
		['name' => 'ANGELOPOLIS', 'state_id' => '2'],
		['name' => 'ANGOSTURA', 'state_id' => '2'],
		['name' => 'ANORI', 'state_id' => '2'],
		['name' => 'ANTIOQUIA', 'state_id' => '2'],
		['name' => 'ANZA', 'state_id' => '2'],
		['name' => 'APARTADO', 'state_id' => '2'],
		['name' => 'ARBOLETES', 'state_id' => '2'],
		['name' => 'ARGELIA', 'state_id' => '2'],
		['name' => 'ARMENIA', 'state_id' => '2'],
		['name' => 'BARBOSA', 'state_id' => '2'],
		['name' => 'BELLO', 'state_id' => '2'],
		['name' => 'BELMIRA', 'state_id' => '2'],
		['name' => 'BETANIA', 'state_id' => '2'],
		['name' => 'BETULIA', 'state_id' => '2'],
		['name' => 'BOLIVAR', 'state_id' => '2'],
		['name' => 'BRICEÑO', 'state_id' => '2'],
		['name' => 'BURITICA', 'state_id' => '2'],
		['name' => 'CACERES', 'state_id' => '2'],
		['name' => 'CAICEDO', 'state_id' => '2'],
		['name' => 'CALDAS', 'state_id' => '2'],
		['name' => 'CAMPAMENTO', 'state_id' => '2'],
		['name' => 'CANASGORDAS', 'state_id' => '2'],
		['name' => 'CARACOLI', 'state_id' => '2'],
		['name' => 'CARAMANTA', 'state_id' => '2'],
		['name' => 'CAREPA', 'state_id' => '2'],
		['name' => 'CARMEN DE VIBORAL', 'state_id' => '2'],
		['name' => 'CAROLINA DEL PRINCIPE', 'state_id' => '2'],
		['name' => 'CAUCASIA', 'state_id' => '2'],
		['name' => 'CHIGORODO', 'state_id' => '2'],
		['name' => 'CISNEROS', 'state_id' => '2'],
		['name' => 'COCORNA', 'state_id' => '2'],
		['name' => 'CONCEPCION', 'state_id' => '2'],
		['name' => 'CONCORDIA', 'state_id' => '2'],
		['name' => 'COPACABANA', 'state_id' => '2'],
		['name' => 'DABEIBA', 'state_id' => '2'],
		['name' => 'DONMATIAS', 'state_id' => '2'],
		['name' => 'EBEJICO', 'state_id' => '2'],
		['name' => 'EL BAGRE', 'state_id' => '2'],
		['name' => 'EL PENOL', 'state_id' => '2'],
		['name' => 'EL RETIRO', 'state_id' => '2'],
		['name' => 'ENTRERRIOS', 'state_id' => '2'],
		['name' => 'ENVIGADO', 'state_id' => '2'],
		['name' => 'FREDONIA', 'state_id' => '2'],
		['name' => 'FRONTINO', 'state_id' => '2'],
		['name' => 'GIRALDO', 'state_id' => '2'],
		['name' => 'GIRARDOTA', 'state_id' => '2'],
		['name' => 'GOMEZ PLATA', 'state_id' => '2'],
		['name' => 'GRANADA', 'state_id' => '2'],
		['name' => 'GUADALUPE', 'state_id' => '2'],
		['name' => 'GUARNE', 'state_id' => '2'],
		['name' => 'GUATAQUE', 'state_id' => '2'],
		['name' => 'HELICONIA', 'state_id' => '2'],
		['name' => 'HISPANIA', 'state_id' => '2'],
		['name' => 'ITAGUI', 'state_id' => '2'],
		['name' => 'ITUANGO', 'state_id' => '2'],
		['name' => 'JARDIN', 'state_id' => '2'],
		['name' => 'JERICO', 'state_id' => '2'],
		['name' => 'LA CEJA', 'state_id' => '2'],
		['name' => 'LA ESTRELLA', 'state_id' => '2'],
		['name' => 'LA PINTADA', 'state_id' => '2'],
		['name' => 'LA UNION', 'state_id' => '2'],
		['name' => 'LIBORINA', 'state_id' => '2'],
		['name' => 'MACEO', 'state_id' => '2'],
		['name' => 'MARINILLA', 'state_id' => '2'],
		['name' => 'MEDELLIN', 'state_id' => '2'],
		['name' => 'MONTEBELLO', 'state_id' => '2'],
		['name' => 'MURINDO', 'state_id' => '2'],
		['name' => 'MUTATA', 'state_id' => '2'],
		['name' => 'NARINO', 'state_id' => '2'],
		['name' => 'NECHI', 'state_id' => '2'],
		['name' => 'NECOCLI', 'state_id' => '2'],
		['name' => 'OLAYA', 'state_id' => '2'],
		['name' => 'PEQUE', 'state_id' => '2'],
		['name' => 'PUEBLORRICO', 'state_id' => '2'],
		['name' => 'PUERTO BERRIO', 'state_id' => '2'],
		['name' => 'PUERTO NARE', 'state_id' => '2'],
		['name' => 'PUERTO TRIUNFO', 'state_id' => '2'],
		['name' => 'REMEDIOS', 'state_id' => '2'],
		['name' => 'RIONEGRO', 'state_id' => '2'],
		['name' => 'SABANALARGA', 'state_id' => '2'],
		['name' => 'SABANETA', 'state_id' => '2'],
		['name' => 'SALGAR', 'state_id' => '2'],
		['name' => 'SAN ANDRES DE CUERQUIA', 'state_id' => '2'],
		['name' => 'SAN CARLOS', 'state_id' => '2'],
		['name' => 'SAN FRANCISCO', 'state_id' => '2'],
		['name' => 'SAN JERONIMO', 'state_id' => '2'],
		['name' => 'SAN JOSE DE LA MONTAÑA', 'state_id' => '2'],
		['name' => 'SAN JUAN DE URABA', 'state_id' => '2'],
		['name' => 'SAN LUIS', 'state_id' => '2'],
		['name' => 'SAN PEDRO DE LOS MILAGROS', 'state_id' => '2'],
		['name' => 'SAN PEDRO DE URABA', 'state_id' => '2'],
		['name' => 'SAN RAFAEL', 'state_id' => '2'],
		['name' => 'SAN ROQUE', 'state_id' => '2'],
		['name' => 'SAN VICENTE', 'state_id' => '2'],
		['name' => 'SANTA BARBARA', 'state_id' => '2'],
		['name' => 'SANTA ROSA DE OSOS', 'state_id' => '2'],
		['name' => 'SANTO DOMINGO', 'state_id' => '2'],
		['name' => 'SANTUARIO', 'state_id' => '2'],
		['name' => 'SEGOVIA', 'state_id' => '2'],
		['name' => 'SONSON', 'state_id' => '2'],
		['name' => 'SOPETRAN', 'state_id' => '2'],
		['name' => 'TAMESIS', 'state_id' => '2'],
		['name' => 'TARAZA', 'state_id' => '2'],
		['name' => 'TARSO', 'state_id' => '2'],
		['name' => 'TITIRIBI', 'state_id' => '2'],
		['name' => 'TOLEDO', 'state_id' => '2'],
		['name' => 'TURBO', 'state_id' => '2'],
		['name' => 'URAMITA', 'state_id' => '2'],
		['name' => 'URRAO', 'state_id' => '2'],
		['name' => 'VALDIVIA', 'state_id' => '2'],
		['name' => 'VALPARAISO', 'state_id' => '2'],
		['name' => 'VEGACHI', 'state_id' => '2'],
		['name' => 'VENECIA', 'state_id' => '2'],
		['name' => 'VIGIA DEL FUERTE', 'state_id' => '2'],
		['name' => 'YALI', 'state_id' => '2'],
		['name' => 'YARUMAL', 'state_id' => '2'],
		['name' => 'YOLOMBO', 'state_id' => '2'],
		['name' => 'YONDO', 'state_id' => '2'],
		['name' => 'ZARAGOZA', 'state_id' => '2'],
		['name' => 'ARAUCA', 'state_id' => '3'],
		['name' => 'ARAUQUITA', 'state_id' => '3'],
		['name' => 'CRAVO NORTE', 'state_id' => '3'],
		['name' => 'FORTUL', 'state_id' => '3'],
		['name' => 'PUERTO RONDON', 'state_id' => '3'],
		['name' => 'SARAVENA', 'state_id' => '3'],
		['name' => 'TAME', 'state_id' => '3'],
		['name' => 'BARANOA', 'state_id' => '4'],
		['name' => 'BARRANQUILLA', 'state_id' => '4'],
		['name' => 'CAMPO DE LA CRUZ', 'state_id' => '4'],
		['name' => 'CANDELARIA', 'state_id' => '4'],
		['name' => 'GALAPA', 'state_id' => '4'],
		['name' => 'JUAN DE ACOSTA', 'state_id' => '4'],
		['name' => 'LURUACO', 'state_id' => '4'],
		['name' => 'MALAMBO', 'state_id' => '4'],
		['name' => 'MANATI', 'state_id' => '4'],
		['name' => 'PALMAR DE VARELA', 'state_id' => '4'],
		['name' => 'PIOJO', 'state_id' => '4'],
		['name' => 'POLO NUEVO', 'state_id' => '4'],
		['name' => 'PONEDERA', 'state_id' => '4'],
		['name' => 'PUERTO COLOMBIA', 'state_id' => '4'],
		['name' => 'REPELON', 'state_id' => '4'],
		['name' => 'SABANAGRANDE', 'state_id' => '4'],
		['name' => 'SABANALARGA', 'state_id' => '4'],
		['name' => 'SANTA LUCIA', 'state_id' => '4'],
		['name' => 'SANTO TOMAS', 'state_id' => '4'],
		['name' => 'SOLEDAD', 'state_id' => '4'],
		['name' => 'SUAN', 'state_id' => '4'],
		['name' => 'TUBARA', 'state_id' => '4'],
		['name' => 'USIACURI', 'state_id' => '4'],
		['name' => 'ACHI', 'state_id' => '5'],
		['name' => 'ALTOS DEL ROSARIO', 'state_id' => '5'],
		['name' => 'ARENAL', 'state_id' => '5'],
		['name' => 'ARJONA', 'state_id' => '5'],
		['name' => 'ARROYOHONDO', 'state_id' => '5'],
		['name' => 'BARRANCO DE LOBA', 'state_id' => '5'],
		['name' => 'BRAZUELO DE PAPAYAL', 'state_id' => '5'],
		['name' => 'CALAMAR', 'state_id' => '5'],
		['name' => 'CANTAGALLO', 'state_id' => '5'],
		['name' => 'CARTAGENA DE INDIAS', 'state_id' => '5'],
		['name' => 'CICUCO', 'state_id' => '5'],
		['name' => 'CLEMENCIA', 'state_id' => '5'],
		['name' => 'CORDOBA', 'state_id' => '5'],
		['name' => 'EL CARMEN DE BOLIVAR', 'state_id' => '5'],
		['name' => 'EL GUAMO', 'state_id' => '5'],
		['name' => 'EL PENION', 'state_id' => '5'],
		['name' => 'HATILLO DE LOBA', 'state_id' => '5'],
		['name' => 'MAGANGUE', 'state_id' => '5'],
		['name' => 'MAHATES', 'state_id' => '5'],
		['name' => 'MARGARITA', 'state_id' => '5'],
		['name' => 'MARIA LA BAJA', 'state_id' => '5'],
		['name' => 'MONTECRISTO', 'state_id' => '5'],
		['name' => 'MORALES', 'state_id' => '5'],
		['name' => 'MORALES', 'state_id' => '5'],
		['name' => 'NOROSI', 'state_id' => '5'],
		['name' => 'PINILLOS', 'state_id' => '5'],
		['name' => 'REGIDOR', 'state_id' => '5'],
		['name' => 'RIO VIEJO', 'state_id' => '5'],
		['name' => 'SAN CRISTOBAL', 'state_id' => '5'],
		['name' => 'SAN ESTANISLAO', 'state_id' => '5'],
		['name' => 'SAN FERNANDO', 'state_id' => '5'],
		['name' => 'SAN JACINTO', 'state_id' => '5'],
		['name' => 'SAN JACINTO DEL CAUCA', 'state_id' => '5'],
		['name' => 'SAN JUAN DE NEPOMUCENO', 'state_id' => '5'],
		['name' => 'SAN MARTIN DE LOBA', 'state_id' => '5'],
		['name' => 'SAN PABLO', 'state_id' => '5'],
		['name' => 'SAN PABLO NORTE', 'state_id' => '5'],
		['name' => 'SANTA CATALINA', 'state_id' => '5'],
		['name' => 'SANTA CRUZ DE MOMPOX', 'state_id' => '5'],
		['name' => 'SANTA ROSA', 'state_id' => '5'],
		['name' => 'SANTA ROSA DEL SUR', 'state_id' => '5'],
		['name' => 'SIMITI', 'state_id' => '5'],
		['name' => 'SOPLAVIENTO', 'state_id' => '5'],
		['name' => 'TALAIGUA NUEVO', 'state_id' => '5'],
		['name' => 'TUQUISIO', 'state_id' => '5'],
		['name' => 'TURBACO', 'state_id' => '5'],
		['name' => 'TURBANA', 'state_id' => '5'],
		['name' => 'VILLANUEVA', 'state_id' => '5'],
		['name' => 'ZAMBRANO', 'state_id' => '5'],
		['name' => 'AQUITANIA', 'state_id' => '6'],
		['name' => 'ARCABUCO', 'state_id' => '6'],
		['name' => 'BELÉN', 'state_id' => '6'],
		['name' => 'BERBEO', 'state_id' => '6'],
		['name' => 'BETÉITIVA', 'state_id' => '6'],
		['name' => 'BOAVITA', 'state_id' => '6'],
		['name' => 'BOYACÁ', 'state_id' => '6'],
		['name' => 'BRICEÑO', 'state_id' => '6'],
		['name' => 'BUENAVISTA', 'state_id' => '6'],
		['name' => 'BUSBANZÁ', 'state_id' => '6'],
		['name' => 'CALDAS', 'state_id' => '6'],
		['name' => 'CAMPO HERMOSO', 'state_id' => '6'],
		['name' => 'CERINZA', 'state_id' => '6'],
		['name' => 'CHINAVITA', 'state_id' => '6'],
		['name' => 'CHIQUINQUIRÁ', 'state_id' => '6'],
		['name' => 'CHÍQUIZA', 'state_id' => '6'],
		['name' => 'CHISCAS', 'state_id' => '6'],
		['name' => 'CHITA', 'state_id' => '6'],
		['name' => 'CHITARAQUE', 'state_id' => '6'],
		['name' => 'CHIVATÁ', 'state_id' => '6'],
		['name' => 'CIÉNEGA', 'state_id' => '6'],
		['name' => 'CÓMBITA', 'state_id' => '6'],
		['name' => 'COPER', 'state_id' => '6'],
		['name' => 'CORRALES', 'state_id' => '6'],
		['name' => 'COVARACHÍA', 'state_id' => '6'],
		['name' => 'CUBARA', 'state_id' => '6'],
		['name' => 'CUCAITA', 'state_id' => '6'],
		['name' => 'CUITIVA', 'state_id' => '6'],
		['name' => 'DUITAMA', 'state_id' => '6'],
		['name' => 'EL COCUY', 'state_id' => '6'],
		['name' => 'EL ESPINO', 'state_id' => '6'],
		['name' => 'FIRAVITOBA', 'state_id' => '6'],
		['name' => 'FLORESTA', 'state_id' => '6'],
		['name' => 'GACHANTIVÁ', 'state_id' => '6'],
		['name' => 'GÁMEZA', 'state_id' => '6'],
		['name' => 'GARAGOA', 'state_id' => '6'],
		['name' => 'GUACAMAYAS', 'state_id' => '6'],
		['name' => 'GÜICÁN', 'state_id' => '6'],
		['name' => 'IZA', 'state_id' => '6'],
		['name' => 'JENESANO', 'state_id' => '6'],
		['name' => 'JERICÓ', 'state_id' => '6'],
		['name' => 'LA UVITA', 'state_id' => '6'],
		['name' => 'LA VICTORIA', 'state_id' => '6'],
		['name' => 'LABRANZA GRANDE', 'state_id' => '6'],
		['name' => 'MACANAL', 'state_id' => '6'],
		['name' => 'MARIPÍ', 'state_id' => '6'],
		['name' => 'MIRAFLORES', 'state_id' => '6'],
		['name' => 'MONGUA', 'state_id' => '6'],
		['name' => 'MONGUÍ', 'state_id' => '6'],
		['name' => 'MONIQUIRÁ', 'state_id' => '6'],
		['name' => 'MOTAVITA', 'state_id' => '6'],
		['name' => 'MUZO', 'state_id' => '6'],
		['name' => 'NOBSA', 'state_id' => '6'],
		['name' => 'NUEVO COLÓN', 'state_id' => '6'],
		['name' => 'OICATÁ', 'state_id' => '6'],
		['name' => 'OTANCHE', 'state_id' => '6'],
		['name' => 'PACHAVITA', 'state_id' => '6'],
		['name' => 'PÁEZ', 'state_id' => '6'],
		['name' => 'PAIPA', 'state_id' => '6'],
		['name' => 'PAJARITO', 'state_id' => '6'],
		['name' => 'PANQUEBA', 'state_id' => '6'],
		['name' => 'PAUNA', 'state_id' => '6'],
		['name' => 'PAYA', 'state_id' => '6'],
		['name' => 'PAZ DE RÍO', 'state_id' => '6'],
		['name' => 'PESCA', 'state_id' => '6'],
		['name' => 'PISBA', 'state_id' => '6'],
		['name' => 'PUERTO BOYACA', 'state_id' => '6'],
		['name' => 'QUÍPAMA', 'state_id' => '6'],
		['name' => 'RAMIRIQUÍ', 'state_id' => '6'],
		['name' => 'RÁQUIRA', 'state_id' => '6'],
		['name' => 'RONDÓN', 'state_id' => '6'],
		['name' => 'SABOYÁ', 'state_id' => '6'],
		['name' => 'SÁCHICA', 'state_id' => '6'],
		['name' => 'SAMACÁ', 'state_id' => '6'],
		['name' => 'SAN EDUARDO', 'state_id' => '6'],
		['name' => 'SAN JOSÉ DE PARE', 'state_id' => '6'],
		['name' => 'SAN LUÍS DE GACENO', 'state_id' => '6'],
		['name' => 'SAN MATEO', 'state_id' => '6'],
		['name' => 'SAN MIGUEL DE SEMA', 'state_id' => '6'],
		['name' => 'SAN PABLO DE BORBUR', 'state_id' => '6'],
		['name' => 'SANTA MARÍA', 'state_id' => '6'],
		['name' => 'SANTA ROSA DE VITERBO', 'state_id' => '6'],
		['name' => 'SANTA SOFÍA', 'state_id' => '6'],
		['name' => 'SANTANA', 'state_id' => '6'],
		['name' => 'SATIVANORTE', 'state_id' => '6'],
		['name' => 'SATIVASUR', 'state_id' => '6'],
		['name' => 'SIACHOQUE', 'state_id' => '6'],
		['name' => 'SOATÁ', 'state_id' => '6'],
		['name' => 'SOCHA', 'state_id' => '6'],
		['name' => 'SOCOTÁ', 'state_id' => '6'],
		['name' => 'SOGAMOSO', 'state_id' => '6'],
		['name' => 'SORA', 'state_id' => '6'],
		['name' => 'SORACÁ', 'state_id' => '6'],
		['name' => 'SOTAQUIRÁ', 'state_id' => '6'],
		['name' => 'SUSACÓN', 'state_id' => '6'],
		['name' => 'SUTARMACHÁN', 'state_id' => '6'],
		['name' => 'TASCO', 'state_id' => '6'],
		['name' => 'TIBANÁ', 'state_id' => '6'],
		['name' => 'TIBASOSA', 'state_id' => '6'],
		['name' => 'TINJACÁ', 'state_id' => '6'],
		['name' => 'TIPACOQUE', 'state_id' => '6'],
		['name' => 'TOCA', 'state_id' => '6'],
		['name' => 'TOGÜÍ', 'state_id' => '6'],
		['name' => 'TÓPAGA', 'state_id' => '6'],
		['name' => 'TOTA', 'state_id' => '6'],
		['name' => 'TUNJA', 'state_id' => '6'],
		['name' => 'TUNUNGUÁ', 'state_id' => '6'],
		['name' => 'TURMEQUÉ', 'state_id' => '6'],
		['name' => 'TUTA', 'state_id' => '6'],
		['name' => 'TUTAZÁ', 'state_id' => '6'],
		['name' => 'UMBITA', 'state_id' => '6'],
		['name' => 'VENTA QUEMADA', 'state_id' => '6'],
		['name' => 'VILLA DE LEYVA', 'state_id' => '6'],
		['name' => 'VIRACACHÁ', 'state_id' => '6'],
		['name' => 'ZETAQUIRA', 'state_id' => '6'],
		['name' => 'AGUADAS', 'state_id' => '7'],
		['name' => 'ANSERMA', 'state_id' => '7'],
		['name' => 'ARANZAZU', 'state_id' => '7'],
		['name' => 'BELALCAZAR', 'state_id' => '7'],
		['name' => 'CHINCHINÁ', 'state_id' => '7'],
		['name' => 'FILADELFIA', 'state_id' => '7'],
		['name' => 'LA DORADA', 'state_id' => '7'],
		['name' => 'LA MERCED', 'state_id' => '7'],
		['name' => 'MANIZALES', 'state_id' => '7'],
		['name' => 'MANZANARES', 'state_id' => '7'],
		['name' => 'MARMATO', 'state_id' => '7'],
		['name' => 'MARQUETALIA', 'state_id' => '7'],
		['name' => 'MARULANDA', 'state_id' => '7'],
		['name' => 'NEIRA', 'state_id' => '7'],
		['name' => 'NORCASIA', 'state_id' => '7'],
		['name' => 'PACORA', 'state_id' => '7'],
		['name' => 'PALESTINA', 'state_id' => '7'],
		['name' => 'PENSILVANIA', 'state_id' => '7'],
		['name' => 'RIOSUCIO', 'state_id' => '7'],
		['name' => 'RISARALDA', 'state_id' => '7'],
		['name' => 'SALAMINA', 'state_id' => '7'],
		['name' => 'SAMANA', 'state_id' => '7'],
		['name' => 'SAN JOSE', 'state_id' => '7'],
		['name' => 'SUPÍA', 'state_id' => '7'],
		['name' => 'VICTORIA', 'state_id' => '7'],
		['name' => 'VILLAMARÍA', 'state_id' => '7'],
		['name' => 'VITERBO', 'state_id' => '7'],
		['name' => 'ALBANIA', 'state_id' => '8'],
		['name' => 'BELÉN ANDAQUIES', 'state_id' => '8'],
		['name' => 'CARTAGENA DEL CHAIRA', 'state_id' => '8'],
		['name' => 'CURILLO', 'state_id' => '8'],
		['name' => 'EL DONCELLO', 'state_id' => '8'],
		['name' => 'EL PAUJIL', 'state_id' => '8'],
		['name' => 'FLORENCIA', 'state_id' => '8'],
		['name' => 'LA MONTAÑITA', 'state_id' => '8'],
		['name' => 'MILÁN', 'state_id' => '8'],
		['name' => 'MORELIA', 'state_id' => '8'],
		['name' => 'PUERTO RICO', 'state_id' => '8'],
		['name' => 'SAN  VICENTE DEL CAGUAN', 'state_id' => '8'],
		['name' => 'SAN JOSÉ DE FRAGUA', 'state_id' => '8'],
		['name' => 'SOLANO', 'state_id' => '8'],
		['name' => 'SOLITA', 'state_id' => '8'],
		['name' => 'VALPARAÍSO', 'state_id' => '8'],
		['name' => 'AGUAZUL', 'state_id' => '9'],
		['name' => 'CHAMEZA', 'state_id' => '9'],
		['name' => 'HATO COROZAL', 'state_id' => '9'],
		['name' => 'LA SALINA', 'state_id' => '9'],
		['name' => 'MANÍ', 'state_id' => '9'],
		['name' => 'MONTERREY', 'state_id' => '9'],
		['name' => 'NUNCHIA', 'state_id' => '9'],
		['name' => 'OROCUE', 'state_id' => '9'],
		['name' => 'PAZ DE ARIPORO', 'state_id' => '9'],
		['name' => 'PORE', 'state_id' => '9'],
		['name' => 'RECETOR', 'state_id' => '9'],
		['name' => 'SABANA LARGA', 'state_id' => '9'],
		['name' => 'SACAMA', 'state_id' => '9'],
		['name' => 'SAN LUIS DE PALENQUE', 'state_id' => '9'],
		['name' => 'TAMARA', 'state_id' => '9'],
		['name' => 'TAURAMENA', 'state_id' => '9'],
		['name' => 'TRINIDAD', 'state_id' => '9'],
		['name' => 'VILLANUEVA', 'state_id' => '9'],
		['name' => 'YOPAL', 'state_id' => '9'],
		['name' => 'ALMAGUER', 'state_id' => '10'],
		['name' => 'ARGELIA', 'state_id' => '10'],
		['name' => 'BALBOA', 'state_id' => '10'],
		['name' => 'BOLÍVAR', 'state_id' => '10'],
		['name' => 'BUENOS AIRES', 'state_id' => '10'],
		['name' => 'CAJIBIO', 'state_id' => '10'],
		['name' => 'CALDONO', 'state_id' => '10'],
		['name' => 'CALOTO', 'state_id' => '10'],
		['name' => 'CORINTO', 'state_id' => '10'],
		['name' => 'EL TAMBO', 'state_id' => '10'],
		['name' => 'FLORENCIA', 'state_id' => '10'],
		['name' => 'GUAPI', 'state_id' => '10'],
		['name' => 'INZA', 'state_id' => '10'],
		['name' => 'JAMBALÓ', 'state_id' => '10'],
		['name' => 'LA SIERRA', 'state_id' => '10'],
		['name' => 'LA VEGA', 'state_id' => '10'],
		['name' => 'LÓPEZ', 'state_id' => '10'],
		['name' => 'MERCADERES', 'state_id' => '10'],
		['name' => 'MIRANDA', 'state_id' => '10'],
		['name' => 'MORALES', 'state_id' => '10'],
		['name' => 'PADILLA', 'state_id' => '10'],
		['name' => 'PÁEZ', 'state_id' => '10'],
		['name' => 'PATIA (EL BORDO)', 'state_id' => '10'],
		['name' => 'PIAMONTE', 'state_id' => '10'],
		['name' => 'PIENDAMO', 'state_id' => '10'],
		['name' => 'POPAYÁN', 'state_id' => '10'],
		['name' => 'PUERTO TEJADA', 'state_id' => '10'],
		['name' => 'PURACE', 'state_id' => '10'],
		['name' => 'ROSAS', 'state_id' => '10'],
		['name' => 'SAN SEBASTIÁN', 'state_id' => '10'],
		['name' => 'SANTA ROSA', 'state_id' => '10'],
		['name' => 'SANTANDER DE QUILICHAO', 'state_id' => '10'],
		['name' => 'SILVIA', 'state_id' => '10'],
		['name' => 'SOTARA', 'state_id' => '10'],
		['name' => 'SUÁREZ', 'state_id' => '10'],
		['name' => 'SUCRE', 'state_id' => '10'],
		['name' => 'TIMBÍO', 'state_id' => '10'],
		['name' => 'TIMBIQUÍ', 'state_id' => '10'],
		['name' => 'TORIBIO', 'state_id' => '10'],
		['name' => 'TOTORO', 'state_id' => '10'],
		['name' => 'VILLA RICA', 'state_id' => '10'],
		['name' => 'AGUACHICA', 'state_id' => '11'],
		['name' => 'AGUSTÍN CODAZZI', 'state_id' => '11'],
		['name' => 'ASTREA', 'state_id' => '11'],
		['name' => 'BECERRIL', 'state_id' => '11'],
		['name' => 'BOSCONIA', 'state_id' => '11'],
		['name' => 'CHIMICHAGUA', 'state_id' => '11'],
		['name' => 'CHIRIGUANÁ', 'state_id' => '11'],
		['name' => 'CURUMANÍ', 'state_id' => '11'],
		['name' => 'EL COPEY', 'state_id' => '11'],
		['name' => 'EL PASO', 'state_id' => '11'],
		['name' => 'GAMARRA', 'state_id' => '11'],
		['name' => 'GONZÁLEZ', 'state_id' => '11'],
		['name' => 'LA GLORIA', 'state_id' => '11'],
		['name' => 'LA JAGUA IBIRICO', 'state_id' => '11'],
		['name' => 'MANAURE BALCÓN DEL CESAR', 'state_id' => '11'],
		['name' => 'PAILITAS', 'state_id' => '11'],
		['name' => 'PELAYA', 'state_id' => '11'],
		['name' => 'PUEBLO BELLO', 'state_id' => '11'],
		['name' => 'RÍO DE ORO', 'state_id' => '11'],
		['name' => 'ROBLES (LA PAZ)', 'state_id' => '11'],
		['name' => 'SAN ALBERTO', 'state_id' => '11'],
		['name' => 'SAN DIEGO', 'state_id' => '11'],
		['name' => 'SAN MARTÍN', 'state_id' => '11'],
		['name' => 'TAMALAMEQUE', 'state_id' => '11'],
		['name' => 'VALLEDUPAR', 'state_id' => '11'],
		['name' => 'ACANDI', 'state_id' => '12'],
		['name' => 'ALTO BAUDO (PIE DE PATO)', 'state_id' => '12'],
		['name' => 'ATRATO', 'state_id' => '12'],
		['name' => 'BAGADO', 'state_id' => '12'],
		['name' => 'BAHIA SOLANO (MUTIS)', 'state_id' => '12'],
		['name' => 'BAJO BAUDO (PIZARRO)', 'state_id' => '12'],
		['name' => 'BOJAYA (BELLAVISTA)', 'state_id' => '12'],
		['name' => 'CANTON DE SAN PABLO', 'state_id' => '12'],
		['name' => 'CARMEN DEL DARIEN', 'state_id' => '12'],
		['name' => 'CERTEGUI', 'state_id' => '12'],
		['name' => 'CONDOTO', 'state_id' => '12'],
		['name' => 'EL CARMEN', 'state_id' => '12'],
		['name' => 'ISTMINA', 'state_id' => '12'],
		['name' => 'JURADO', 'state_id' => '12'],
		['name' => 'LITORAL DEL SAN JUAN', 'state_id' => '12'],
		['name' => 'LLORO', 'state_id' => '12'],
		['name' => 'MEDIO ATRATO', 'state_id' => '12'],
		['name' => 'MEDIO BAUDO (BOCA DE PEPE)', 'state_id' => '12'],
		['name' => 'MEDIO SAN JUAN', 'state_id' => '12'],
		['name' => 'NOVITA', 'state_id' => '12'],
		['name' => 'NUQUI', 'state_id' => '12'],
		['name' => 'QUIBDO', 'state_id' => '12'],
		['name' => 'RIO IRO', 'state_id' => '12'],
		['name' => 'RIO QUITO', 'state_id' => '12'],
		['name' => 'RIOSUCIO', 'state_id' => '12'],
		['name' => 'SAN JOSE DEL PALMAR', 'state_id' => '12'],
		['name' => 'SIPI', 'state_id' => '12'],
		['name' => 'TADO', 'state_id' => '12'],
		['name' => 'UNGUIA', 'state_id' => '12'],
		['name' => 'UNIÓN PANAMERICANA', 'state_id' => '12'],
		['name' => 'AYAPEL', 'state_id' => '13'],
		['name' => 'BUENAVISTA', 'state_id' => '13'],
		['name' => 'CANALETE', 'state_id' => '13'],
		['name' => 'CERETÉ', 'state_id' => '13'],
		['name' => 'CHIMA', 'state_id' => '13'],
		['name' => 'CHINÚ', 'state_id' => '13'],
		['name' => 'CIENAGA DE ORO', 'state_id' => '13'],
		['name' => 'COTORRA', 'state_id' => '13'],
		['name' => 'LA APARTADA', 'state_id' => '13'],
		['name' => 'LORICA', 'state_id' => '13'],
		['name' => 'LOS CÓRDOBAS', 'state_id' => '13'],
		['name' => 'MOMIL', 'state_id' => '13'],
		['name' => 'MONTELÍBANO', 'state_id' => '13'],
		['name' => 'MONTERÍA', 'state_id' => '13'],
		['name' => 'MOÑITOS', 'state_id' => '13'],
		['name' => 'PLANETA RICA', 'state_id' => '13'],
		['name' => 'PUEBLO NUEVO', 'state_id' => '13'],
		['name' => 'PUERTO ESCONDIDO', 'state_id' => '13'],
		['name' => 'PUERTO LIBERTADOR', 'state_id' => '13'],
		['name' => 'PURÍSIMA', 'state_id' => '13'],
		['name' => 'SAHAGÚN', 'state_id' => '13'],
		['name' => 'SAN ANDRÉS SOTAVENTO', 'state_id' => '13'],
		['name' => 'SAN ANTERO', 'state_id' => '13'],
		['name' => 'SAN BERNARDO VIENTO', 'state_id' => '13'],
		['name' => 'SAN CARLOS', 'state_id' => '13'],
		['name' => 'SAN PELAYO', 'state_id' => '13'],
		['name' => 'TIERRALTA', 'state_id' => '13'],
		['name' => 'VALENCIA', 'state_id' => '13'],
		['name' => 'AGUA DE DIOS', 'state_id' => '14'],
		['name' => 'ALBAN', 'state_id' => '14'],
		['name' => 'ANAPOIMA', 'state_id' => '14'],
		['name' => 'ANOLAIMA', 'state_id' => '14'],
		['name' => 'ARBELAEZ', 'state_id' => '14'],
		['name' => 'BELTRÁN', 'state_id' => '14'],
		['name' => 'BITUIMA', 'state_id' => '14'],
		['name' => 'BOGOTÁ DC', 'state_id' => '14'],
		['name' => 'BOJACÁ', 'state_id' => '14'],
		['name' => 'CABRERA', 'state_id' => '14'],
		['name' => 'CACHIPAY', 'state_id' => '14'],
		['name' => 'CAJICÁ', 'state_id' => '14'],
		['name' => 'CAPARRAPÍ', 'state_id' => '14'],
		['name' => 'CAQUEZA', 'state_id' => '14'],
		['name' => 'CARMEN DE CARUPA', 'state_id' => '14'],
		['name' => 'CHAGUANÍ', 'state_id' => '14'],
		['name' => 'CHIA', 'state_id' => '14'],
		['name' => 'CHIPAQUE', 'state_id' => '14'],
		['name' => 'CHOACHÍ', 'state_id' => '14'],
		['name' => 'CHOCONTÁ', 'state_id' => '14'],
		['name' => 'COGUA', 'state_id' => '14'],
		['name' => 'COTA', 'state_id' => '14'],
		['name' => 'CUCUNUBÁ', 'state_id' => '14'],
		['name' => 'EL COLEGIO', 'state_id' => '14'],
		['name' => 'EL PEÑÓN', 'state_id' => '14'],
		['name' => 'EL ROSAL1', 'state_id' => '14'],
		['name' => 'FACATATIVA', 'state_id' => '14'],
		['name' => 'FÓMEQUE', 'state_id' => '14'],
		['name' => 'FOSCA', 'state_id' => '14'],
		['name' => 'FUNZA', 'state_id' => '14'],
		['name' => 'FÚQUENE', 'state_id' => '14'],
		['name' => 'FUSAGASUGA', 'state_id' => '14'],
		['name' => 'GACHALÁ', 'state_id' => '14'],
		['name' => 'GACHANCIPÁ', 'state_id' => '14'],
		['name' => 'GACHETA', 'state_id' => '14'],
		['name' => 'GAMA', 'state_id' => '14'],
		['name' => 'GIRARDOT', 'state_id' => '14'],
		['name' => 'GRANADA2', 'state_id' => '14'],
		['name' => 'GUACHETÁ', 'state_id' => '14'],
		['name' => 'GUADUAS', 'state_id' => '14'],
		['name' => 'GUASCA', 'state_id' => '14'],
		['name' => 'GUATAQUÍ', 'state_id' => '14'],
		['name' => 'GUATAVITA', 'state_id' => '14'],
		['name' => 'GUAYABAL DE SIQUIMA', 'state_id' => '14'],
		['name' => 'GUAYABETAL', 'state_id' => '14'],
		['name' => 'GUTIÉRREZ', 'state_id' => '14'],
		['name' => 'JERUSALÉN', 'state_id' => '14'],
		['name' => 'JUNÍN', 'state_id' => '14'],
		['name' => 'LA CALERA', 'state_id' => '14'],
		['name' => 'LA MESA', 'state_id' => '14'],
		['name' => 'LA PALMA', 'state_id' => '14'],
		['name' => 'LA PEÑA', 'state_id' => '14'],
		['name' => 'LA VEGA', 'state_id' => '14'],
		['name' => 'LENGUAZAQUE', 'state_id' => '14'],
		['name' => 'MACHETÁ', 'state_id' => '14'],
		['name' => 'MADRID', 'state_id' => '14'],
		['name' => 'MANTA', 'state_id' => '14'],
		['name' => 'MEDINA', 'state_id' => '14'],
		['name' => 'MOSQUERA', 'state_id' => '14'],
		['name' => 'NARIÑO', 'state_id' => '14'],
		['name' => 'NEMOCÓN', 'state_id' => '14'],
		['name' => 'NILO', 'state_id' => '14'],
		['name' => 'NIMAIMA', 'state_id' => '14'],
		['name' => 'NOCAIMA', 'state_id' => '14'],
		['name' => 'OSPINA PÉREZ', 'state_id' => '14'],
		['name' => 'PACHO', 'state_id' => '14'],
		['name' => 'PAIME', 'state_id' => '14'],
		['name' => 'PANDI', 'state_id' => '14'],
		['name' => 'PARATEBUENO', 'state_id' => '14'],
		['name' => 'PASCA', 'state_id' => '14'],
		['name' => 'PUERTO SALGAR', 'state_id' => '14'],
		['name' => 'PULÍ', 'state_id' => '14'],
		['name' => 'QUEBRADANEGRA', 'state_id' => '14'],
		['name' => 'QUETAME', 'state_id' => '14'],
		['name' => 'QUIPILE', 'state_id' => '14'],
		['name' => 'RAFAEL REYES', 'state_id' => '14'],
		['name' => 'RICAURTE', 'state_id' => '14'],
		['name' => 'SAN  ANTONIO DEL  TEQUENDAMA', 'state_id' => '14'],
		['name' => 'SAN BERNARDO', 'state_id' => '14'],
		['name' => 'SAN CAYETANO', 'state_id' => '14'],
		['name' => 'SAN FRANCISCO', 'state_id' => '14'],
		['name' => 'SAN JUAN DE RIOSECO', 'state_id' => '14'],
		['name' => 'SASAIMA', 'state_id' => '14'],
		['name' => 'SESQUILÉ', 'state_id' => '14'],
		['name' => 'SIBATÉ', 'state_id' => '14'],
		['name' => 'SILVANIA', 'state_id' => '14'],
		['name' => 'SIMIJACA', 'state_id' => '14'],
		['name' => 'SOACHA', 'state_id' => '14'],
		['name' => 'SOPO', 'state_id' => '14'],
		['name' => 'SUBACHOQUE', 'state_id' => '14'],
		['name' => 'SUESCA', 'state_id' => '14'],
		['name' => 'SUPATÁ', 'state_id' => '14'],
		['name' => 'SUSA', 'state_id' => '14'],
		['name' => 'SUTATAUSA', 'state_id' => '14'],
		['name' => 'TABIO', 'state_id' => '14'],
		['name' => 'TAUSA', 'state_id' => '14'],
		['name' => 'TENA', 'state_id' => '14'],
		['name' => 'TENJO', 'state_id' => '14'],
		['name' => 'TIBACUY', 'state_id' => '14'],
		['name' => 'TIBIRITA', 'state_id' => '14'],
		['name' => 'TOCAIMA', 'state_id' => '14'],
		['name' => 'TOCANCIPÁ', 'state_id' => '14'],
		['name' => 'TOPAIPÍ', 'state_id' => '14'],
		['name' => 'UBALÁ', 'state_id' => '14'],
		['name' => 'UBAQUE', 'state_id' => '14'],
		['name' => 'UBATÉ', 'state_id' => '14'],
		['name' => 'UNE', 'state_id' => '14'],
		['name' => 'UTICA', 'state_id' => '14'],
		['name' => 'VERGARA', 'state_id' => '14'],
		['name' => 'VIANI', 'state_id' => '14'],
		['name' => 'VILLA GOMEZ', 'state_id' => '14'],
		['name' => 'VILLA PINZÓN', 'state_id' => '14'],
		['name' => 'VILLETA', 'state_id' => '14'],
		['name' => 'VIOTA', 'state_id' => '14'],
		['name' => 'YACOPÍ', 'state_id' => '14'],
		['name' => 'ZIPACÓN', 'state_id' => '14'],
		['name' => 'ZIPAQUIRÁ', 'state_id' => '14'],
		['name' => 'BARRANCO MINAS', 'state_id' => '15'],
		['name' => 'CACAHUAL', 'state_id' => '15'],
		['name' => 'INÍRIDA', 'state_id' => '15'],
		['name' => 'LA GUADALUPE', 'state_id' => '15'],
		['name' => 'MAPIRIPANA', 'state_id' => '15'],
		['name' => 'MORICHAL', 'state_id' => '15'],
		['name' => 'PANA PANA', 'state_id' => '15'],
		['name' => 'PUERTO COLOMBIA', 'state_id' => '15'],
		['name' => 'SAN FELIPE', 'state_id' => '15'],
		['name' => 'CALAMAR', 'state_id' => '16'],
		['name' => 'EL RETORNO', 'state_id' => '16'],
		['name' => 'MIRAFLOREZ', 'state_id' => '16'],
		['name' => 'SAN JOSÉ DEL GUAVIARE', 'state_id' => '16'],
		['name' => 'ACEVEDO', 'state_id' => '17'],
		['name' => 'AGRADO', 'state_id' => '17'],
		['name' => 'AIPE', 'state_id' => '17'],
		['name' => 'ALGECIRAS', 'state_id' => '17'],
		['name' => 'ALTAMIRA', 'state_id' => '17'],
		['name' => 'BARAYA', 'state_id' => '17'],
		['name' => 'CAMPO ALEGRE', 'state_id' => '17'],
		['name' => 'COLOMBIA', 'state_id' => '17'],
		['name' => 'ELIAS', 'state_id' => '17'],
		['name' => 'GARZÓN', 'state_id' => '17'],
		['name' => 'GIGANTE', 'state_id' => '17'],
		['name' => 'GUADALUPE', 'state_id' => '17'],
		['name' => 'HOBO', 'state_id' => '17'],
		['name' => 'IQUIRA', 'state_id' => '17'],
		['name' => 'ISNOS', 'state_id' => '17'],
		['name' => 'LA ARGENTINA', 'state_id' => '17'],
		['name' => 'LA PLATA', 'state_id' => '17'],
		['name' => 'NATAGA', 'state_id' => '17'],
		['name' => 'NEIVA', 'state_id' => '17'],
		['name' => 'OPORAPA', 'state_id' => '17'],
		['name' => 'PAICOL', 'state_id' => '17'],
		['name' => 'PALERMO', 'state_id' => '17'],
		['name' => 'PALESTINA', 'state_id' => '17'],
		['name' => 'PITAL', 'state_id' => '17'],
		['name' => 'PITALITO', 'state_id' => '17'],
		['name' => 'RIVERA', 'state_id' => '17'],
		['name' => 'SALADO BLANCO', 'state_id' => '17'],
		['name' => 'SAN AGUSTÍN', 'state_id' => '17'],
		['name' => 'SANTA MARIA', 'state_id' => '17'],
		['name' => 'SUAZA', 'state_id' => '17'],
		['name' => 'TARQUI', 'state_id' => '17'],
		['name' => 'TELLO', 'state_id' => '17'],
		['name' => 'TERUEL', 'state_id' => '17'],
		['name' => 'TESALIA', 'state_id' => '17'],
		['name' => 'TIMANA', 'state_id' => '17'],
		['name' => 'VILLAVIEJA', 'state_id' => '17'],
		['name' => 'YAGUARA', 'state_id' => '17'],
		['name' => 'ALBANIA', 'state_id' => '18'],
		['name' => 'BARRANCAS', 'state_id' => '18'],
		['name' => 'DIBULLA', 'state_id' => '18'],
		['name' => 'DISTRACCIÓN', 'state_id' => '18'],
		['name' => 'EL MOLINO', 'state_id' => '18'],
		['name' => 'FONSECA', 'state_id' => '18'],
		['name' => 'HATO NUEVO', 'state_id' => '18'],
		['name' => 'LA JAGUA DEL PILAR', 'state_id' => '18'],
		['name' => 'MAICAO', 'state_id' => '18'],
		['name' => 'MANAURE', 'state_id' => '18'],
		['name' => 'RIOHACHA', 'state_id' => '18'],
		['name' => 'SAN JUAN DEL CESAR', 'state_id' => '18'],
		['name' => 'URIBIA', 'state_id' => '18'],
		['name' => 'URUMITA', 'state_id' => '18'],
		['name' => 'VILLANUEVA', 'state_id' => '18'],
		['name' => 'ALGARROBO', 'state_id' => '19'],
		['name' => 'ARACATACA', 'state_id' => '19'],
		['name' => 'ARIGUANI', 'state_id' => '19'],
		['name' => 'CERRO SAN ANTONIO', 'state_id' => '19'],
		['name' => 'CHIVOLO', 'state_id' => '19'],
		['name' => 'CIENAGA', 'state_id' => '19'],
		['name' => 'CONCORDIA', 'state_id' => '19'],
		['name' => 'EL BANCO', 'state_id' => '19'],
		['name' => 'EL PIÑON', 'state_id' => '19'],
		['name' => 'EL RETEN', 'state_id' => '19'],
		['name' => 'FUNDACION', 'state_id' => '19'],
		['name' => 'GUAMAL', 'state_id' => '19'],
		['name' => 'NUEVA GRANADA', 'state_id' => '19'],
		['name' => 'PEDRAZA', 'state_id' => '19'],
		['name' => 'PIJIÑO DEL CARMEN', 'state_id' => '19'],
		['name' => 'PIVIJAY', 'state_id' => '19'],
		['name' => 'PLATO', 'state_id' => '19'],
		['name' => 'PUEBLO VIEJO', 'state_id' => '19'],
		['name' => 'REMOLINO', 'state_id' => '19'],
		['name' => 'SABANAS DE SAN ANGEL', 'state_id' => '19'],
		['name' => 'SALAMINA', 'state_id' => '19'],
		['name' => 'SAN SEBASTIAN DE BUENAVISTA', 'state_id' => '19'],
		['name' => 'SAN ZENON', 'state_id' => '19'],
		['name' => 'SANTA ANA', 'state_id' => '19'],
		['name' => 'SANTA BARBARA DE PINTO', 'state_id' => '19'],
		['name' => 'SANTA MARTA', 'state_id' => '19'],
		['name' => 'SITIONUEVO', 'state_id' => '19'],
		['name' => 'TENERIFE', 'state_id' => '19'],
		['name' => 'ZAPAYAN', 'state_id' => '19'],
		['name' => 'ZONA BANANERA', 'state_id' => '19'],
		['name' => 'ACACIAS', 'state_id' => '20'],
		['name' => 'BARRANCA DE UPIA', 'state_id' => '20'],
		['name' => 'CABUYARO', 'state_id' => '20'],
		['name' => 'CASTILLA LA NUEVA', 'state_id' => '20'],
		['name' => 'CUBARRAL', 'state_id' => '20'],
		['name' => 'CUMARAL', 'state_id' => '20'],
		['name' => 'EL CALVARIO', 'state_id' => '20'],
		['name' => 'EL CASTILLO', 'state_id' => '20'],
		['name' => 'EL DORADO', 'state_id' => '20'],
		['name' => 'FUENTE DE ORO', 'state_id' => '20'],
		['name' => 'GRANADA', 'state_id' => '20'],
		['name' => 'GUAMAL', 'state_id' => '20'],
		['name' => 'LA MACARENA', 'state_id' => '20'],
		['name' => 'LA URIBE', 'state_id' => '20'],
		['name' => 'LEJANÍAS', 'state_id' => '20'],
		['name' => 'MAPIRIPÁN', 'state_id' => '20'],
		['name' => 'MESETAS', 'state_id' => '20'],
		['name' => 'PUERTO CONCORDIA', 'state_id' => '20'],
		['name' => 'PUERTO GAITÁN', 'state_id' => '20'],
		['name' => 'PUERTO LLERAS', 'state_id' => '20'],
		['name' => 'PUERTO LÓPEZ', 'state_id' => '20'],
		['name' => 'PUERTO RICO', 'state_id' => '20'],
		['name' => 'RESTREPO', 'state_id' => '20'],
		['name' => 'SAN  JUAN DE ARAMA', 'state_id' => '20'],
		['name' => 'SAN CARLOS GUAROA', 'state_id' => '20'],
		['name' => 'SAN JUANITO', 'state_id' => '20'],
		['name' => 'SAN MARTÍN', 'state_id' => '20'],
		['name' => 'VILLAVICENCIO', 'state_id' => '20'],
		['name' => 'VISTA HERMOSA', 'state_id' => '20'],
		['name' => 'ALBAN', 'state_id' => '21'],
		['name' => 'ALDAÑA', 'state_id' => '21'],
		['name' => 'ANCUYA', 'state_id' => '21'],
		['name' => 'ARBOLEDA', 'state_id' => '21'],
		['name' => 'BARBACOAS', 'state_id' => '21'],
		['name' => 'BELEN', 'state_id' => '21'],
		['name' => 'BUESACO', 'state_id' => '21'],
		['name' => 'CHACHAGUI', 'state_id' => '21'],
		['name' => 'COLON (GENOVA)', 'state_id' => '21'],
		['name' => 'CONSACA', 'state_id' => '21'],
		['name' => 'CONTADERO', 'state_id' => '21'],
		['name' => 'CORDOBA', 'state_id' => '21'],
		['name' => 'CUASPUD', 'state_id' => '21'],
		['name' => 'CUMBAL', 'state_id' => '21'],
		['name' => 'CUMBITARA', 'state_id' => '21'],
		['name' => 'EL CHARCO', 'state_id' => '21'],
		['name' => 'EL PEÑOL', 'state_id' => '21'],
		['name' => 'EL ROSARIO', 'state_id' => '21'],
		['name' => 'EL TABLÓN', 'state_id' => '21'],
		['name' => 'EL TAMBO', 'state_id' => '21'],
		['name' => 'FUNES', 'state_id' => '21'],
		['name' => 'GUACHUCAL', 'state_id' => '21'],
		['name' => 'GUAITARILLA', 'state_id' => '21'],
		['name' => 'GUALMATAN', 'state_id' => '21'],
		['name' => 'ILES', 'state_id' => '21'],
		['name' => 'IMUES', 'state_id' => '21'],
		['name' => 'IPIALES', 'state_id' => '21'],
		['name' => 'LA CRUZ', 'state_id' => '21'],
		['name' => 'LA FLORIDA', 'state_id' => '21'],
		['name' => 'LA LLANADA', 'state_id' => '21'],
		['name' => 'LA TOLA', 'state_id' => '21'],
		['name' => 'LA UNION', 'state_id' => '21'],
		['name' => 'LEIVA', 'state_id' => '21'],
		['name' => 'LINARES', 'state_id' => '21'],
		['name' => 'LOS ANDES', 'state_id' => '21'],
		['name' => 'MAGUI', 'state_id' => '21'],
		['name' => 'MALLAMA', 'state_id' => '21'],
		['name' => 'MOSQUEZA', 'state_id' => '21'],
		['name' => 'NARIÑO', 'state_id' => '21'],
		['name' => 'OLAYA HERRERA', 'state_id' => '21'],
		['name' => 'OSPINA', 'state_id' => '21'],
		['name' => 'PASTO', 'state_id' => '21'],
		['name' => 'PIZARRO', 'state_id' => '21'],
		['name' => 'POLICARPA', 'state_id' => '21'],
		['name' => 'POTOSI', 'state_id' => '21'],
		['name' => 'PROVIDENCIA', 'state_id' => '21'],
		['name' => 'PUERRES', 'state_id' => '21'],
		['name' => 'PUPIALES', 'state_id' => '21'],
		['name' => 'RICAURTE', 'state_id' => '21'],
		['name' => 'ROBERTO PAYAN', 'state_id' => '21'],
		['name' => 'SAMANIEGO', 'state_id' => '21'],
		['name' => 'SAN BERNARDO', 'state_id' => '21'],
		['name' => 'SAN LORENZO', 'state_id' => '21'],
		['name' => 'SAN PABLO', 'state_id' => '21'],
		['name' => 'SAN PEDRO DE CARTAGO', 'state_id' => '21'],
		['name' => 'SANDONA', 'state_id' => '21'],
		['name' => 'SANTA BARBARA', 'state_id' => '21'],
		['name' => 'SANTACRUZ', 'state_id' => '21'],
		['name' => 'SAPUYES', 'state_id' => '21'],
		['name' => 'TAMINANGO', 'state_id' => '21'],
		['name' => 'TANGUA', 'state_id' => '21'],
		['name' => 'TUMACO', 'state_id' => '21'],
		['name' => 'TUQUERRES', 'state_id' => '21'],
		['name' => 'YACUANQUER', 'state_id' => '21'],
		['name' => 'ABREGO', 'state_id' => '22'],
		['name' => 'ARBOLEDAS', 'state_id' => '22'],
		['name' => 'BOCHALEMA', 'state_id' => '22'],
		['name' => 'BUCARASICA', 'state_id' => '22'],
		['name' => 'CÁCHIRA', 'state_id' => '22'],
		['name' => 'CÁCOTA', 'state_id' => '22'],
		['name' => 'CHINÁCOTA', 'state_id' => '22'],
		['name' => 'CHITAGÁ', 'state_id' => '22'],
		['name' => 'CONVENCIÓN', 'state_id' => '22'],
		['name' => 'CÚCUTA', 'state_id' => '22'],
		['name' => 'CUCUTILLA', 'state_id' => '22'],
		['name' => 'DURANIA', 'state_id' => '22'],
		['name' => 'EL CARMEN', 'state_id' => '22'],
		['name' => 'EL TARRA', 'state_id' => '22'],
		['name' => 'EL ZULIA', 'state_id' => '22'],
		['name' => 'GRAMALOTE', 'state_id' => '22'],
		['name' => 'HACARI', 'state_id' => '22'],
		['name' => 'HERRÁN', 'state_id' => '22'],
		['name' => 'LA ESPERANZA', 'state_id' => '22'],
		['name' => 'LA PLAYA', 'state_id' => '22'],
		['name' => 'LABATECA', 'state_id' => '22'],
		['name' => 'LOS PATIOS', 'state_id' => '22'],
		['name' => 'LOURDES', 'state_id' => '22'],
		['name' => 'MUTISCUA', 'state_id' => '22'],
		['name' => 'OCAÑA', 'state_id' => '22'],
		['name' => 'PAMPLONA', 'state_id' => '22'],
		['name' => 'PAMPLONITA', 'state_id' => '22'],
		['name' => 'PUERTO SANTANDER', 'state_id' => '22'],
		['name' => 'RAGONVALIA', 'state_id' => '22'],
		['name' => 'SALAZAR', 'state_id' => '22'],
		['name' => 'SAN CALIXTO', 'state_id' => '22'],
		['name' => 'SAN CAYETANO', 'state_id' => '22'],
		['name' => 'SANTIAGO', 'state_id' => '22'],
		['name' => 'SARDINATA', 'state_id' => '22'],
		['name' => 'SILOS', 'state_id' => '22'],
		['name' => 'TEORAMA', 'state_id' => '22'],
		['name' => 'TIBÚ', 'state_id' => '22'],
		['name' => 'TOLEDO', 'state_id' => '22'],
		['name' => 'VILLA CARO', 'state_id' => '22'],
		['name' => 'VILLA DEL ROSARIO', 'state_id' => '22'],
		['name' => 'COLÓN', 'state_id' => '23'],
		['name' => 'MOCOA', 'state_id' => '23'],
		['name' => 'ORITO', 'state_id' => '23'],
		['name' => 'PUERTO ASÍS', 'state_id' => '23'],
		['name' => 'PUERTO CAYCEDO', 'state_id' => '23'],
		['name' => 'PUERTO GUZMÁN', 'state_id' => '23'],
		['name' => 'PUERTO LEGUÍZAMO', 'state_id' => '23'],
		['name' => 'SAN FRANCISCO', 'state_id' => '23'],
		['name' => 'SAN MIGUEL', 'state_id' => '23'],
		['name' => 'SANTIAGO', 'state_id' => '23'],
		['name' => 'SIBUNDOY', 'state_id' => '23'],
		['name' => 'VALLE DEL GUAMUEZ', 'state_id' => '23'],
		['name' => 'VILLAGARZÓN', 'state_id' => '23'],
		['name' => 'ARMENIA', 'state_id' => '24'],
		['name' => 'BUENAVISTA', 'state_id' => '24'],
		['name' => 'CALARCÁ', 'state_id' => '24'],
		['name' => 'CIRCASIA', 'state_id' => '24'],
		['name' => 'CÓRDOBA', 'state_id' => '24'],
		['name' => 'FILANDIA', 'state_id' => '24'],
		['name' => 'GÉNOVA', 'state_id' => '24'],
		['name' => 'LA TEBAIDA', 'state_id' => '24'],
		['name' => 'MONTENEGRO', 'state_id' => '24'],
		['name' => 'PIJAO', 'state_id' => '24'],
		['name' => 'QUIMBAYA', 'state_id' => '24'],
		['name' => 'SALENTO', 'state_id' => '24'],
		['name' => 'APIA', 'state_id' => '25'],
		['name' => 'BALBOA', 'state_id' => '25'],
		['name' => 'BELÉN DE UMBRÍA', 'state_id' => '25'],
		['name' => 'DOS QUEBRADAS', 'state_id' => '25'],
		['name' => 'GUATICA', 'state_id' => '25'],
		['name' => 'LA CELIA', 'state_id' => '25'],
		['name' => 'LA VIRGINIA', 'state_id' => '25'],
		['name' => 'MARSELLA', 'state_id' => '25'],
		['name' => 'MISTRATO', 'state_id' => '25'],
		['name' => 'PEREIRA', 'state_id' => '25'],
		['name' => 'PUEBLO RICO', 'state_id' => '25'],
		['name' => 'QUINCHÍA', 'state_id' => '25'],
		['name' => 'SANTA ROSA DE CABAL', 'state_id' => '25'],
		['name' => 'SANTUARIO', 'state_id' => '25'],
		['name' => 'PROVIDENCIA', 'state_id' => '26'],
		['name' => 'SAN ANDRES', 'state_id' => '26'],
		['name' => 'SANTA CATALINA', 'state_id' => '26'],
		['name' => 'AGUADA', 'state_id' => '27'],
		['name' => 'ALBANIA', 'state_id' => '27'],
		['name' => 'ARATOCA', 'state_id' => '27'],
		['name' => 'BARBOSA', 'state_id' => '27'],
		['name' => 'BARICHARA', 'state_id' => '27'],
		['name' => 'BARRANCABERMEJA', 'state_id' => '27'],
		['name' => 'BETULIA', 'state_id' => '27'],
		['name' => 'BOLÍVAR', 'state_id' => '27'],
		['name' => 'BUCARAMANGA', 'state_id' => '27'],
		['name' => 'CABRERA', 'state_id' => '27'],
		['name' => 'CALIFORNIA', 'state_id' => '27'],
		['name' => 'CAPITANEJO', 'state_id' => '27'],
		['name' => 'CARCASI', 'state_id' => '27'],
		['name' => 'CEPITA', 'state_id' => '27'],
		['name' => 'CERRITO', 'state_id' => '27'],
		['name' => 'CHARALÁ', 'state_id' => '27'],
		['name' => 'CHARTA', 'state_id' => '27'],
		['name' => 'CHIMA', 'state_id' => '27'],
		['name' => 'CHIPATÁ', 'state_id' => '27'],
		['name' => 'CIMITARRA', 'state_id' => '27'],
		['name' => 'CONCEPCIÓN', 'state_id' => '27'],
		['name' => 'CONFINES', 'state_id' => '27'],
		['name' => 'CONTRATACIÓN', 'state_id' => '27'],
		['name' => 'COROMORO', 'state_id' => '27'],
		['name' => 'CURITÍ', 'state_id' => '27'],
		['name' => 'EL CARMEN', 'state_id' => '27'],
		['name' => 'EL GUACAMAYO', 'state_id' => '27'],
		['name' => 'EL PEÑÓN', 'state_id' => '27'],
		['name' => 'EL PLAYÓN', 'state_id' => '27'],
		['name' => 'ENCINO', 'state_id' => '27'],
		['name' => 'ENCISO', 'state_id' => '27'],
		['name' => 'FLORIÁN', 'state_id' => '27'],
		['name' => 'FLORIDABLANCA', 'state_id' => '27'],
		['name' => 'GALÁN', 'state_id' => '27'],
		['name' => 'GAMBITA', 'state_id' => '27'],
		['name' => 'GIRÓN', 'state_id' => '27'],
		['name' => 'GUACA', 'state_id' => '27'],
		['name' => 'GUADALUPE', 'state_id' => '27'],
		['name' => 'GUAPOTA', 'state_id' => '27'],
		['name' => 'GUAVATÁ', 'state_id' => '27'],
		['name' => 'GUEPSA', 'state_id' => '27'],
		['name' => 'HATO', 'state_id' => '27'],
		['name' => 'JESÚS MARIA', 'state_id' => '27'],
		['name' => 'JORDÁN', 'state_id' => '27'],
		['name' => 'LA BELLEZA', 'state_id' => '27'],
		['name' => 'LA PAZ', 'state_id' => '27'],
		['name' => 'LANDAZURI', 'state_id' => '27'],
		['name' => 'LEBRIJA', 'state_id' => '27'],
		['name' => 'LOS SANTOS', 'state_id' => '27'],
		['name' => 'MACARAVITA', 'state_id' => '27'],
		['name' => 'MÁLAGA', 'state_id' => '27'],
		['name' => 'MATANZA', 'state_id' => '27'],
		['name' => 'MOGOTES', 'state_id' => '27'],
		['name' => 'MOLAGAVITA', 'state_id' => '27'],
		['name' => 'OCAMONTE', 'state_id' => '27'],
		['name' => 'OIBA', 'state_id' => '27'],
		['name' => 'ONZAGA', 'state_id' => '27'],
		['name' => 'PALMAR', 'state_id' => '27'],
		['name' => 'PALMAS DEL SOCORRO', 'state_id' => '27'],
		['name' => 'PÁRAMO', 'state_id' => '27'],
		['name' => 'PIEDECUESTA', 'state_id' => '27'],
		['name' => 'PINCHOTE', 'state_id' => '27'],
		['name' => 'PUENTE NACIONAL', 'state_id' => '27'],
		['name' => 'PUERTO PARRA', 'state_id' => '27'],
		['name' => 'PUERTO WILCHES', 'state_id' => '27'],
		['name' => 'RIONEGRO', 'state_id' => '27'],
		['name' => 'SABANA DE TORRES', 'state_id' => '27'],
		['name' => 'SAN ANDRÉS', 'state_id' => '27'],
		['name' => 'SAN BENITO', 'state_id' => '27'],
		['name' => 'SAN GIL', 'state_id' => '27'],
		['name' => 'SAN JOAQUÍN', 'state_id' => '27'],
		['name' => 'SAN JOSÉ DE MIRANDA', 'state_id' => '27'],
		['name' => 'SAN MIGUEL', 'state_id' => '27'],
		['name' => 'SAN VICENTE DE CHUCURÍ', 'state_id' => '27'],
		['name' => 'SANTA BÁRBARA', 'state_id' => '27'],
		['name' => 'SANTA HELENA', 'state_id' => '27'],
		['name' => 'SIMACOTA', 'state_id' => '27'],
		['name' => 'SOCORRO', 'state_id' => '27'],
		['name' => 'SUAITA', 'state_id' => '27'],
		['name' => 'SUCRE', 'state_id' => '27'],
		['name' => 'SURATA', 'state_id' => '27'],
		['name' => 'TONA', 'state_id' => '27'],
		['name' => 'VALLE SAN JOSÉ', 'state_id' => '27'],
		['name' => 'VÉLEZ', 'state_id' => '27'],
		['name' => 'VETAS', 'state_id' => '27'],
		['name' => 'VILLANUEVA', 'state_id' => '27'],
		['name' => 'ZAPATOCA', 'state_id' => '27'],
		['name' => 'BUENAVISTA', 'state_id' => '28'],
		['name' => 'CAIMITO', 'state_id' => '28'],
		['name' => 'CHALÁN', 'state_id' => '28'],
		['name' => 'COLOSO', 'state_id' => '28'],
		['name' => 'COROZAL', 'state_id' => '28'],
		['name' => 'EL ROBLE', 'state_id' => '28'],
		['name' => 'GALERAS', 'state_id' => '28'],
		['name' => 'GUARANDA', 'state_id' => '28'],
		['name' => 'LA UNIÓN', 'state_id' => '28'],
		['name' => 'LOS PALMITOS', 'state_id' => '28'],
		['name' => 'MAJAGUAL', 'state_id' => '28'],
		['name' => 'MORROA', 'state_id' => '28'],
		['name' => 'OVEJAS', 'state_id' => '28'],
		['name' => 'PALMITO', 'state_id' => '28'],
		['name' => 'SAMPUES', 'state_id' => '28'],
		['name' => 'SAN BENITO ABAD', 'state_id' => '28'],
		['name' => 'SAN JUAN DE BETULIA', 'state_id' => '28'],
		['name' => 'SAN MARCOS', 'state_id' => '28'],
		['name' => 'SAN ONOFRE', 'state_id' => '28'],
		['name' => 'SAN PEDRO', 'state_id' => '28'],
		['name' => 'SINCÉ', 'state_id' => '28'],
		['name' => 'SINCELEJO', 'state_id' => '28'],
		['name' => 'SUCRE', 'state_id' => '28'],
		['name' => 'TOLÚ', 'state_id' => '28'],
		['name' => 'TOLUVIEJO', 'state_id' => '28'],
		['name' => 'ALPUJARRA', 'state_id' => '29'],
		['name' => 'ALVARADO', 'state_id' => '29'],
		['name' => 'AMBALEMA', 'state_id' => '29'],
		['name' => 'ANZOATEGUI', 'state_id' => '29'],
		['name' => 'ARMERO (GUAYABAL)', 'state_id' => '29'],
		['name' => 'ATACO', 'state_id' => '29'],
		['name' => 'CAJAMARCA', 'state_id' => '29'],
		['name' => 'CARMEN DE APICALÁ', 'state_id' => '29'],
		['name' => 'CASABIANCA', 'state_id' => '29'],
		['name' => 'CHAPARRAL', 'state_id' => '29'],
		['name' => 'COELLO', 'state_id' => '29'],
		['name' => 'COYAIMA', 'state_id' => '29'],
		['name' => 'CUNDAY', 'state_id' => '29'],
		['name' => 'DOLORES', 'state_id' => '29'],
		['name' => 'ESPINAL', 'state_id' => '29'],
		['name' => 'FALÁN', 'state_id' => '29'],
		['name' => 'FLANDES', 'state_id' => '29'],
		['name' => 'FRESNO', 'state_id' => '29'],
		['name' => 'GUAMO', 'state_id' => '29'],
		['name' => 'HERVEO', 'state_id' => '29'],
		['name' => 'HONDA', 'state_id' => '29'],
		['name' => 'IBAGUÉ', 'state_id' => '29'],
		['name' => 'ICONONZO', 'state_id' => '29'],
		['name' => 'LÉRIDA', 'state_id' => '29'],
		['name' => 'LÍBANO', 'state_id' => '29'],
		['name' => 'MARIQUITA', 'state_id' => '29'],
		['name' => 'MELGAR', 'state_id' => '29'],
		['name' => 'MURILLO', 'state_id' => '29'],
		['name' => 'NATAGAIMA', 'state_id' => '29'],
		['name' => 'ORTEGA', 'state_id' => '29'],
		['name' => 'PALOCABILDO', 'state_id' => '29'],
		['name' => 'PIEDRAS PLANADAS', 'state_id' => '29'],
		['name' => 'PRADO', 'state_id' => '29'],
		['name' => 'PURIFICACIÓN', 'state_id' => '29'],
		['name' => 'RIOBLANCO', 'state_id' => '29'],
		['name' => 'RONCESVALLES', 'state_id' => '29'],
		['name' => 'ROVIRA', 'state_id' => '29'],
		['name' => 'SALDAÑA', 'state_id' => '29'],
		['name' => 'SAN ANTONIO', 'state_id' => '29'],
		['name' => 'SAN LUIS', 'state_id' => '29'],
		['name' => 'SANTA ISABEL', 'state_id' => '29'],
		['name' => 'SUÁREZ', 'state_id' => '29'],
		['name' => 'VALLE DE SAN JUAN', 'state_id' => '29'],
		['name' => 'VENADILLO', 'state_id' => '29'],
		['name' => 'VILLAHERMOSA', 'state_id' => '29'],
		['name' => 'VILLARRICA', 'state_id' => '29'],
		['name' => 'ALCALÁ', 'state_id' => '30'],
		['name' => 'ANDALUCÍA', 'state_id' => '30'],
		['name' => 'ANSERMA NUEVO', 'state_id' => '30'],
		['name' => 'ARGELIA', 'state_id' => '30'],
		['name' => 'BOLÍVAR', 'state_id' => '30'],
		['name' => 'BUENAVENTURA', 'state_id' => '30'],
		['name' => 'BUGA', 'state_id' => '30'],
		['name' => 'BUGALAGRANDE', 'state_id' => '30'],
		['name' => 'CAICEDONIA', 'state_id' => '30'],
		['name' => 'CALI', 'state_id' => '30'],
		['name' => 'CALIMA (DARIEN)', 'state_id' => '30'],
		['name' => 'CANDELARIA', 'state_id' => '30'],
		['name' => 'CARTAGO', 'state_id' => '30'],
		['name' => 'DAGUA', 'state_id' => '30'],
		['name' => 'EL AGUILA', 'state_id' => '30'],
		['name' => 'EL CAIRO', 'state_id' => '30'],
		['name' => 'EL CERRITO', 'state_id' => '30'],
		['name' => 'EL DOVIO', 'state_id' => '30'],
		['name' => 'FLORIDA', 'state_id' => '30'],
		['name' => 'GINEBRA GUACARI', 'state_id' => '30'],
		['name' => 'JAMUNDÍ', 'state_id' => '30'],
		['name' => 'LA CUMBRE', 'state_id' => '30'],
		['name' => 'LA UNIÓN', 'state_id' => '30'],
		['name' => 'LA VICTORIA', 'state_id' => '30'],
		['name' => 'OBANDO', 'state_id' => '30'],
		['name' => 'PALMIRA', 'state_id' => '30'],
		['name' => 'PRADERA', 'state_id' => '30'],
		['name' => 'RESTREPO', 'state_id' => '30'],
		['name' => 'RIO FRÍO', 'state_id' => '30'],
		['name' => 'ROLDANILLO', 'state_id' => '30'],
		['name' => 'SAN PEDRO', 'state_id' => '30'],
		['name' => 'SEVILLA', 'state_id' => '30'],
		['name' => 'TORO', 'state_id' => '30'],
		['name' => 'TRUJILLO', 'state_id' => '30'],
		['name' => 'TULÚA', 'state_id' => '30'],
		['name' => 'ULLOA', 'state_id' => '30'],
		['name' => 'VERSALLES', 'state_id' => '30'],
		['name' => 'VIJES', 'state_id' => '30'],
		['name' => 'YOTOCO', 'state_id' => '30'],
		['name' => 'YUMBO', 'state_id' => '30'],
		['name' => 'ZARZAL', 'state_id' => '30'],
		['name' => 'CARURÚ', 'state_id' => '31'],
		['name' => 'MITÚ', 'state_id' => '31'],
		['name' => 'PACOA', 'state_id' => '31'],
		['name' => 'PAPUNAUA', 'state_id' => '31'],
		['name' => 'TARAIRA', 'state_id' => '31'],
		['name' => 'YAVARATÉ', 'state_id' => '31'],
		['name' => 'CUMARIBO', 'state_id' => '32'],
		['name' => 'LA PRIMAVERA', 'state_id' => '32'],
		['name' => 'PUERTO CARREÑO', 'state_id' => '32'],
		['name' => 'SANTA ROSALIA', 'state_id' => '32'],


		    
		]);
    }
}
